/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ParkingSpace } from "./ParkingSpace";
import { ParkingSpaceCountArgs } from "./ParkingSpaceCountArgs";
import { ParkingSpaceFindManyArgs } from "./ParkingSpaceFindManyArgs";
import { ParkingSpaceFindUniqueArgs } from "./ParkingSpaceFindUniqueArgs";
import { CreateParkingSpaceArgs } from "./CreateParkingSpaceArgs";
import { UpdateParkingSpaceArgs } from "./UpdateParkingSpaceArgs";
import { DeleteParkingSpaceArgs } from "./DeleteParkingSpaceArgs";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { Event } from "../../event/base/Event";
import { ParkingSpaceService } from "../parkingSpace.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ParkingSpace)
export class ParkingSpaceResolverBase {
  constructor(
    protected readonly service: ParkingSpaceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ParkingSpace",
    action: "read",
    possession: "any",
  })
  async _parkingSpacesMeta(
    @graphql.Args() args: ParkingSpaceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ParkingSpace])
  @nestAccessControl.UseRoles({
    resource: "ParkingSpace",
    action: "read",
    possession: "any",
  })
  async parkingSpaces(
    @graphql.Args() args: ParkingSpaceFindManyArgs
  ): Promise<ParkingSpace[]> {
    return this.service.parkingSpaces(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ParkingSpace, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ParkingSpace",
    action: "read",
    possession: "own",
  })
  async parkingSpace(
    @graphql.Args() args: ParkingSpaceFindUniqueArgs
  ): Promise<ParkingSpace | null> {
    const result = await this.service.parkingSpace(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ParkingSpace)
  @nestAccessControl.UseRoles({
    resource: "ParkingSpace",
    action: "create",
    possession: "any",
  })
  async createParkingSpace(
    @graphql.Args() args: CreateParkingSpaceArgs
  ): Promise<ParkingSpace> {
    return await this.service.createParkingSpace({
      ...args,
      data: {
        ...args.data,

        event: args.data.event
          ? {
              connect: args.data.event,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ParkingSpace)
  @nestAccessControl.UseRoles({
    resource: "ParkingSpace",
    action: "update",
    possession: "any",
  })
  async updateParkingSpace(
    @graphql.Args() args: UpdateParkingSpaceArgs
  ): Promise<ParkingSpace | null> {
    try {
      return await this.service.updateParkingSpace({
        ...args,
        data: {
          ...args.data,

          event: args.data.event
            ? {
                connect: args.data.event,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ParkingSpace)
  @nestAccessControl.UseRoles({
    resource: "ParkingSpace",
    action: "delete",
    possession: "any",
  })
  async deleteParkingSpace(
    @graphql.Args() args: DeleteParkingSpaceArgs
  ): Promise<ParkingSpace | null> {
    try {
      return await this.service.deleteParkingSpace(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @graphql.Parent() parent: ParkingSpace,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Review], { name: "reviews" })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @graphql.Parent() parent: ParkingSpace,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Event, {
    nullable: true,
    name: "event",
  })
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  async getEvent(
    @graphql.Parent() parent: ParkingSpace
  ): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
