/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import {
  IsOptional,
  ValidateNested,
  IsString,
  IsNumber,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { BookingCreateNestedManyWithoutParkingSpacesInput } from "./BookingCreateNestedManyWithoutParkingSpacesInput";
import { Type } from "class-transformer";
import { EventWhereUniqueInput } from "../../event/base/EventWhereUniqueInput";
import { ReviewCreateNestedManyWithoutParkingSpacesInput } from "./ReviewCreateNestedManyWithoutParkingSpacesInput";

@InputType()
class ParkingSpaceCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  availability?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => BookingCreateNestedManyWithoutParkingSpacesInput,
  })
  @ValidateNested()
  @Type(() => BookingCreateNestedManyWithoutParkingSpacesInput)
  @IsOptional()
  @Field(() => BookingCreateNestedManyWithoutParkingSpacesInput, {
    nullable: true,
  })
  bookings?: BookingCreateNestedManyWithoutParkingSpacesInput;

  @ApiProperty({
    required: false,
    type: () => EventWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EventWhereUniqueInput)
  @IsOptional()
  @Field(() => EventWhereUniqueInput, {
    nullable: true,
  })
  event?: EventWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  owner?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  photos?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutParkingSpacesInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutParkingSpacesInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutParkingSpacesInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutParkingSpacesInput;
}

export { ParkingSpaceCreateInput as ParkingSpaceCreateInput };
